window.esdocSearchIndex = [
  [
    "@carwin/flag-generator/src/divisions/bend.js~bend",
    "class/src/divisions/Bend.js~Bend.html",
    "<span>Bend</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Bend.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/border.js~border",
    "class/src/divisions/Border.js~Border.html",
    "<span>Border</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Border.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/canton.js~canton",
    "class/src/divisions/Canton.js~Canton.html",
    "<span>Canton</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Canton.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/chevron.js~chevron",
    "class/src/divisions/Chevron.js~Chevron.html",
    "<span>Chevron</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Chevron.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/cross.js~cross",
    "class/src/divisions/Cross.js~Cross.html",
    "<span>Cross</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Cross.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/division.js~division",
    "class/src/division.js~Division.html",
    "<span>Division</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/division.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/fesses.js~fesses",
    "class/src/divisions/Fesses.js~Fesses.html",
    "<span>Fesses</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Fesses.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/fusil.js~fusil",
    "class/src/divisions/Fusil.js~Fusil.html",
    "<span>Fusil</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Fusil.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/lozenge.js~lozenge",
    "class/src/divisions/Lozenge.js~Lozenge.html",
    "<span>Lozenge</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Lozenge.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/pales.js~pales",
    "class/src/divisions/Pales.js~Pales.html",
    "<span>Pales</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Pales.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/pall.js~pall",
    "class/src/divisions/Pall.js~Pall.html",
    "<span>Pall</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Pall.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/divisions/saltire.js~saltire",
    "class/src/divisions/Saltire.js~Saltire.html",
    "<span>Saltire</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/divisions/Saltire.js</span>",
    "class"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~converthex",
    "function/index.html#static-function-convertHex",
    "<span>convertHex</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~findgreaternumber",
    "function/index.html#static-function-findGreaterNumber",
    "<span>findGreaterNumber</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~generatecanvas",
    "function/index.html#static-function-generateCanvas",
    "<span>generateCanvas</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~generatecolor",
    "function/index.html#static-function-generateColor",
    "<span>generateColor</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~generatecount",
    "function/index.html#static-function-generateCount",
    "<span>generateCount</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~generateseed",
    "function/index.html#static-function-generateSeed",
    "<span>generateSeed</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~generateseedmultiplier",
    "function/index.html#static-function-generateSeedMultiplier",
    "<span>generateSeedMultiplier</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~getlastdigit",
    "function/index.html#static-function-getLastDigit",
    "<span>getLastDigit</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~hextorgb",
    "function/index.html#static-function-hexToRgb",
    "<span>hexToRgb</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~modifyseed",
    "function/index.html#static-function-modifySeed",
    "<span>modifySeed</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~processaspectratiostring",
    "function/index.html#static-function-processAspectRatioString",
    "<span>processAspectRatioString</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~pseudoshuffle",
    "function/index.html#static-function-pseudoShuffle",
    "<span>pseudoShuffle</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~randomhex",
    "function/index.html#static-function-randomHex",
    "<span>randomHex</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/utilities.js~setdimensionsfromaspectobject",
    "function/index.html#static-function-setDimensionsFromAspectObject",
    "<span>setDimensionsFromAspectObject</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/utilities.js</span>",
    "function"
  ],
  [
    "@carwin/flag-generator/src/settings.js~settings",
    "variable/index.html#static-variable-settings",
    "<span>settings</span> <span class=\"search-result-import-path\">@carwin/flag-generator/src/settings.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/division.js",
    "file/src/division.js.html",
    "src/division.js",
    "file"
  ],
  [
    "src/division.js~division#color",
    "class/src/division.js~Division.html#instance-member-color",
    "src/division.js~Division#color",
    "member"
  ],
  [
    "src/division.js~division#constructor",
    "class/src/division.js~Division.html#instance-constructor-constructor",
    "src/division.js~Division#constructor",
    "method"
  ],
  [
    "src/division.js~division#count",
    "class/src/division.js~Division.html#instance-member-count",
    "src/division.js~Division#count",
    "member"
  ],
  [
    "src/division.js~division#limit",
    "class/src/division.js~Division.html#instance-member-limit",
    "src/division.js~Division#limit",
    "member"
  ],
  [
    "src/division.js~division#seed",
    "class/src/division.js~Division.html#instance-member-seed",
    "src/division.js~Division#seed",
    "member"
  ],
  [
    "src/division.js~division#seedmultiplier",
    "class/src/division.js~Division.html#instance-member-seedMultiplier",
    "src/division.js~Division#seedMultiplier",
    "member"
  ],
  [
    "src/division.test.js",
    "file/src/division.test.js.html",
    "src/division.test.js",
    "file"
  ],
  [
    "src/divisions/bend.js",
    "file/src/divisions/Bend.js.html",
    "src/divisions/Bend.js",
    "file"
  ],
  [
    "src/divisions/bend.js~bend#border",
    "class/src/divisions/Bend.js~Bend.html#instance-member-border",
    "src/divisions/Bend.js~Bend#border",
    "member"
  ],
  [
    "src/divisions/bend.js~bend#bordercolor",
    "class/src/divisions/Bend.js~Bend.html#instance-member-borderColor",
    "src/divisions/Bend.js~Bend#borderColor",
    "member"
  ],
  [
    "src/divisions/bend.js~bend#borderwidth",
    "class/src/divisions/Bend.js~Bend.html#instance-member-borderWidth",
    "src/divisions/Bend.js~Bend#borderWidth",
    "member"
  ],
  [
    "src/divisions/bend.js~bend#constructor",
    "class/src/divisions/Bend.js~Bend.html#instance-constructor-constructor",
    "src/divisions/Bend.js~Bend#constructor",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#direction",
    "class/src/divisions/Bend.js~Bend.html#instance-member-direction",
    "src/divisions/Bend.js~Bend#direction",
    "member"
  ],
  [
    "src/divisions/bend.js~bend#draw",
    "class/src/divisions/Bend.js~Bend.html#instance-method-draw",
    "src/divisions/Bend.js~Bend#draw",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#drawinstructions",
    "class/src/divisions/Bend.js~Bend.html#instance-method-drawInstructions",
    "src/divisions/Bend.js~Bend#drawInstructions",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#drawinstructionsdexter",
    "class/src/divisions/Bend.js~Bend.html#instance-method-drawInstructionsDexter",
    "src/divisions/Bend.js~Bend#drawInstructionsDexter",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#drawinstructionssinister",
    "class/src/divisions/Bend.js~Bend.html#instance-method-drawInstructionsSinister",
    "src/divisions/Bend.js~Bend#drawInstructionsSinister",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#generatedirection",
    "class/src/divisions/Bend.js~Bend.html#instance-method-generateDirection",
    "src/divisions/Bend.js~Bend#generateDirection",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#party",
    "class/src/divisions/Bend.js~Bend.html#instance-member-party",
    "src/divisions/Bend.js~Bend#party",
    "member"
  ],
  [
    "src/divisions/bend.js~bend#shiftstep",
    "class/src/divisions/Bend.js~Bend.html#instance-method-shiftStep",
    "src/divisions/Bend.js~Bend#shiftStep",
    "method"
  ],
  [
    "src/divisions/bend.js~bend#width",
    "class/src/divisions/Bend.js~Bend.html#instance-member-width",
    "src/divisions/Bend.js~Bend#width",
    "member"
  ],
  [
    "src/divisions/bend.test.js",
    "file/src/divisions/Bend.test.js.html",
    "src/divisions/Bend.test.js",
    "file"
  ],
  [
    "src/divisions/border.js",
    "file/src/divisions/Border.js.html",
    "src/divisions/Border.js",
    "file"
  ],
  [
    "src/divisions/border.js~border#borderwidth",
    "class/src/divisions/Border.js~Border.html#instance-member-borderWidth",
    "src/divisions/Border.js~Border#borderWidth",
    "member"
  ],
  [
    "src/divisions/border.js~border#constructor",
    "class/src/divisions/Border.js~Border.html#instance-constructor-constructor",
    "src/divisions/Border.js~Border#constructor",
    "method"
  ],
  [
    "src/divisions/border.js~border#draw",
    "class/src/divisions/Border.js~Border.html#instance-method-draw",
    "src/divisions/Border.js~Border#draw",
    "method"
  ],
  [
    "src/divisions/canton.js",
    "file/src/divisions/Canton.js.html",
    "src/divisions/Canton.js",
    "file"
  ],
  [
    "src/divisions/canton.js~canton#aspect",
    "class/src/divisions/Canton.js~Canton.html#instance-member-aspect",
    "src/divisions/Canton.js~Canton#aspect",
    "member"
  ],
  [
    "src/divisions/canton.js~canton#constructor",
    "class/src/divisions/Canton.js~Canton.html#instance-constructor-constructor",
    "src/divisions/Canton.js~Canton#constructor",
    "method"
  ],
  [
    "src/divisions/canton.js~canton#draw",
    "class/src/divisions/Canton.js~Canton.html#instance-method-draw",
    "src/divisions/Canton.js~Canton#draw",
    "method"
  ],
  [
    "src/divisions/canton.js~canton#drawinstructions",
    "class/src/divisions/Canton.js~Canton.html#instance-method-drawInstructions",
    "src/divisions/Canton.js~Canton#drawInstructions",
    "method"
  ],
  [
    "src/divisions/chevron.js",
    "file/src/divisions/Chevron.js.html",
    "src/divisions/Chevron.js",
    "file"
  ],
  [
    "src/divisions/chevron.js~chevron#border",
    "class/src/divisions/Chevron.js~Chevron.html#instance-member-border",
    "src/divisions/Chevron.js~Chevron#border",
    "member"
  ],
  [
    "src/divisions/chevron.js~chevron#bordercolor",
    "class/src/divisions/Chevron.js~Chevron.html#instance-member-borderColor",
    "src/divisions/Chevron.js~Chevron#borderColor",
    "member"
  ],
  [
    "src/divisions/chevron.js~chevron#borderwidth",
    "class/src/divisions/Chevron.js~Chevron.html#instance-member-borderWidth",
    "src/divisions/Chevron.js~Chevron#borderWidth",
    "member"
  ],
  [
    "src/divisions/chevron.js~chevron#constructor",
    "class/src/divisions/Chevron.js~Chevron.html#instance-constructor-constructor",
    "src/divisions/Chevron.js~Chevron#constructor",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#direction",
    "class/src/divisions/Chevron.js~Chevron.html#instance-member-direction",
    "src/divisions/Chevron.js~Chevron#direction",
    "member"
  ],
  [
    "src/divisions/chevron.js~chevron#draw",
    "class/src/divisions/Chevron.js~Chevron.html#instance-method-draw",
    "src/divisions/Chevron.js~Chevron#draw",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#drawinstructions",
    "class/src/divisions/Chevron.js~Chevron.html#instance-method-drawInstructions",
    "src/divisions/Chevron.js~Chevron#drawInstructions",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#drawinstructionsfesswise",
    "class/src/divisions/Chevron.js~Chevron.html#instance-method-drawInstructionsFesswise",
    "src/divisions/Chevron.js~Chevron#drawInstructionsFesswise",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#drawinstructionspalewise",
    "class/src/divisions/Chevron.js~Chevron.html#instance-method-drawInstructionsPalewise",
    "src/divisions/Chevron.js~Chevron#drawInstructionsPalewise",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#generatedirection",
    "class/src/divisions/Chevron.js~Chevron.html#instance-method-generateDirection",
    "src/divisions/Chevron.js~Chevron#generateDirection",
    "method"
  ],
  [
    "src/divisions/chevron.js~chevron#width",
    "class/src/divisions/Chevron.js~Chevron.html#instance-member-width",
    "src/divisions/Chevron.js~Chevron#width",
    "member"
  ],
  [
    "src/divisions/cross.js",
    "file/src/divisions/Cross.js.html",
    "src/divisions/Cross.js",
    "file"
  ],
  [
    "src/divisions/cross.js~cross#border",
    "class/src/divisions/Cross.js~Cross.html#instance-member-border",
    "src/divisions/Cross.js~Cross#border",
    "member"
  ],
  [
    "src/divisions/cross.js~cross#bordercolor",
    "class/src/divisions/Cross.js~Cross.html#instance-member-borderColor",
    "src/divisions/Cross.js~Cross#borderColor",
    "member"
  ],
  [
    "src/divisions/cross.js~cross#borderwidth",
    "class/src/divisions/Cross.js~Cross.html#instance-member-borderWidth",
    "src/divisions/Cross.js~Cross#borderWidth",
    "member"
  ],
  [
    "src/divisions/cross.js~cross#constructor",
    "class/src/divisions/Cross.js~Cross.html#instance-constructor-constructor",
    "src/divisions/Cross.js~Cross#constructor",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#crosstype",
    "class/src/divisions/Cross.js~Cross.html#instance-member-crossType",
    "src/divisions/Cross.js~Cross#crossType",
    "member"
  ],
  [
    "src/divisions/cross.js~cross#crosswidth",
    "class/src/divisions/Cross.js~Cross.html#instance-member-crossWidth",
    "src/divisions/Cross.js~Cross#crossWidth",
    "member"
  ],
  [
    "src/divisions/cross.js~cross#draw",
    "class/src/divisions/Cross.js~Cross.html#instance-method-draw",
    "src/divisions/Cross.js~Cross#draw",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#drawgreekcross",
    "class/src/divisions/Cross.js~Cross.html#instance-method-drawGreekCross",
    "src/divisions/Cross.js~Cross#drawGreekCross",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#drawnordiccross",
    "class/src/divisions/Cross.js~Cross.html#instance-method-drawNordicCross",
    "src/divisions/Cross.js~Cross#drawNordicCross",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#drawsymmetriccross",
    "class/src/divisions/Cross.js~Cross.html#instance-method-drawSymmetricCross",
    "src/divisions/Cross.js~Cross#drawSymmetricCross",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#generateborderwidth",
    "class/src/divisions/Cross.js~Cross.html#instance-method-generateBorderWidth",
    "src/divisions/Cross.js~Cross#generateBorderWidth",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#generatecrosstype",
    "class/src/divisions/Cross.js~Cross.html#instance-method-generateCrossType",
    "src/divisions/Cross.js~Cross#generateCrossType",
    "method"
  ],
  [
    "src/divisions/cross.js~cross#generatecrosswidth",
    "class/src/divisions/Cross.js~Cross.html#instance-method-generateCrossWidth",
    "src/divisions/Cross.js~Cross#generateCrossWidth",
    "method"
  ],
  [
    "src/divisions/cross.test.js",
    "file/src/divisions/Cross.test.js.html",
    "src/divisions/Cross.test.js",
    "file"
  ],
  [
    "src/divisions/fesses.js",
    "file/src/divisions/Fesses.js.html",
    "src/divisions/Fesses.js",
    "file"
  ],
  [
    "src/divisions/fesses.js~fesses#constructor",
    "class/src/divisions/Fesses.js~Fesses.html#instance-constructor-constructor",
    "src/divisions/Fesses.js~Fesses#constructor",
    "method"
  ],
  [
    "src/divisions/fesses.js~fesses#draw",
    "class/src/divisions/Fesses.js~Fesses.html#instance-method-draw",
    "src/divisions/Fesses.js~Fesses#draw",
    "method"
  ],
  [
    "src/divisions/fesses.js~fesses#gappercentage",
    "class/src/divisions/Fesses.js~Fesses.html#instance-member-gapPercentage",
    "src/divisions/Fesses.js~Fesses#gapPercentage",
    "member"
  ],
  [
    "src/divisions/fusil.js",
    "file/src/divisions/Fusil.js.html",
    "src/divisions/Fusil.js",
    "file"
  ],
  [
    "src/divisions/fusil.js~fusil#constructor",
    "class/src/divisions/Fusil.js~Fusil.html#instance-constructor-constructor",
    "src/divisions/Fusil.js~Fusil#constructor",
    "method"
  ],
  [
    "src/divisions/fusil.js~fusil#draw",
    "class/src/divisions/Fusil.js~Fusil.html#instance-method-draw",
    "src/divisions/Fusil.js~Fusil#draw",
    "method"
  ],
  [
    "src/divisions/fusil.test.js",
    "file/src/divisions/Fusil.test.js.html",
    "src/divisions/Fusil.test.js",
    "file"
  ],
  [
    "src/divisions/lozenge.js",
    "file/src/divisions/Lozenge.js.html",
    "src/divisions/Lozenge.js",
    "file"
  ],
  [
    "src/divisions/lozenge.js~lozenge#constructor",
    "class/src/divisions/Lozenge.js~Lozenge.html#instance-constructor-constructor",
    "src/divisions/Lozenge.js~Lozenge#constructor",
    "method"
  ],
  [
    "src/divisions/lozenge.js~lozenge#draw",
    "class/src/divisions/Lozenge.js~Lozenge.html#instance-method-draw",
    "src/divisions/Lozenge.js~Lozenge#draw",
    "method"
  ],
  [
    "src/divisions/lozenge.test.js",
    "file/src/divisions/Lozenge.test.js.html",
    "src/divisions/Lozenge.test.js",
    "file"
  ],
  [
    "src/divisions/pales.js",
    "file/src/divisions/Pales.js.html",
    "src/divisions/Pales.js",
    "file"
  ],
  [
    "src/divisions/pales.js~pales#constructor",
    "class/src/divisions/Pales.js~Pales.html#instance-constructor-constructor",
    "src/divisions/Pales.js~Pales#constructor",
    "method"
  ],
  [
    "src/divisions/pales.js~pales#draw",
    "class/src/divisions/Pales.js~Pales.html#instance-method-draw",
    "src/divisions/Pales.js~Pales#draw",
    "method"
  ],
  [
    "src/divisions/pales.js~pales#gappercentage",
    "class/src/divisions/Pales.js~Pales.html#instance-member-gapPercentage",
    "src/divisions/Pales.js~Pales#gapPercentage",
    "member"
  ],
  [
    "src/divisions/pall.js",
    "file/src/divisions/Pall.js.html",
    "src/divisions/Pall.js",
    "file"
  ],
  [
    "src/divisions/pall.js~pall#border",
    "class/src/divisions/Pall.js~Pall.html#instance-member-border",
    "src/divisions/Pall.js~Pall#border",
    "member"
  ],
  [
    "src/divisions/pall.js~pall#bordercolor",
    "class/src/divisions/Pall.js~Pall.html#instance-member-borderColor",
    "src/divisions/Pall.js~Pall#borderColor",
    "member"
  ],
  [
    "src/divisions/pall.js~pall#borderwidth",
    "class/src/divisions/Pall.js~Pall.html#instance-member-borderWidth",
    "src/divisions/Pall.js~Pall#borderWidth",
    "member"
  ],
  [
    "src/divisions/pall.js~pall#constructor",
    "class/src/divisions/Pall.js~Pall.html#instance-constructor-constructor",
    "src/divisions/Pall.js~Pall#constructor",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#direction",
    "class/src/divisions/Pall.js~Pall.html#instance-member-direction",
    "src/divisions/Pall.js~Pall#direction",
    "member"
  ],
  [
    "src/divisions/pall.js~pall#draw",
    "class/src/divisions/Pall.js~Pall.html#instance-method-draw",
    "src/divisions/Pall.js~Pall#draw",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#drawinstructions",
    "class/src/divisions/Pall.js~Pall.html#instance-method-drawInstructions",
    "src/divisions/Pall.js~Pall#drawInstructions",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#drawinstructionsfesswise",
    "class/src/divisions/Pall.js~Pall.html#instance-method-drawInstructionsFesswise",
    "src/divisions/Pall.js~Pall#drawInstructionsFesswise",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#drawinstructionspalewise",
    "class/src/divisions/Pall.js~Pall.html#instance-method-drawInstructionsPalewise",
    "src/divisions/Pall.js~Pall#drawInstructionsPalewise",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#generatedirection",
    "class/src/divisions/Pall.js~Pall.html#instance-method-generateDirection",
    "src/divisions/Pall.js~Pall#generateDirection",
    "method"
  ],
  [
    "src/divisions/pall.js~pall#width",
    "class/src/divisions/Pall.js~Pall.html#instance-member-width",
    "src/divisions/Pall.js~Pall#width",
    "member"
  ],
  [
    "src/divisions/saltire.js",
    "file/src/divisions/Saltire.js.html",
    "src/divisions/Saltire.js",
    "file"
  ],
  [
    "src/divisions/saltire.js~saltire#border",
    "class/src/divisions/Saltire.js~Saltire.html#instance-member-border",
    "src/divisions/Saltire.js~Saltire#border",
    "member"
  ],
  [
    "src/divisions/saltire.js~saltire#borderwidth",
    "class/src/divisions/Saltire.js~Saltire.html#instance-member-borderWidth",
    "src/divisions/Saltire.js~Saltire#borderWidth",
    "member"
  ],
  [
    "src/divisions/saltire.js~saltire#constructor",
    "class/src/divisions/Saltire.js~Saltire.html#instance-constructor-constructor",
    "src/divisions/Saltire.js~Saltire#constructor",
    "method"
  ],
  [
    "src/divisions/saltire.js~saltire#draw",
    "class/src/divisions/Saltire.js~Saltire.html#instance-method-draw",
    "src/divisions/Saltire.js~Saltire#draw",
    "method"
  ],
  [
    "src/divisions/saltire.js~saltire#generatesaltireborder",
    "class/src/divisions/Saltire.js~Saltire.html#instance-method-generateSaltireBorder",
    "src/divisions/Saltire.js~Saltire#generateSaltireBorder",
    "method"
  ],
  [
    "src/divisions/saltire.js~saltire#generatesaltirewidth",
    "class/src/divisions/Saltire.js~Saltire.html#instance-method-generateSaltireWidth",
    "src/divisions/Saltire.js~Saltire#generateSaltireWidth",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/settings.js",
    "file/src/settings.js.html",
    "src/settings.js",
    "file"
  ],
  [
    "src/utilities.js",
    "file/src/utilities.js.html",
    "src/utilities.js",
    "file"
  ],
  [
    "src/utilities.js~colorobject",
    "typedef/index.html#static-typedef-ColorObject",
    "src/utilities.js~ColorObject",
    "typedef"
  ],
  [
    "src/utilities.test.js",
    "file/src/utilities.test.js.html",
    "src/utilities.test.js",
    "file"
  ]
]